name: Image Recommender Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Jupyter Notebook
        run: |
          pip install ipykernel
          python -m ipykernel install --user --name=myenv
          jupyter nbconvert --to notebook --execute main.ipynb --ExecutePreprocessor.kernel_name=myenv
